# Prometheus Configuration v2.45.0
# Main configuration file for monitoring the Automated Meeting Minutes System
# Defines global settings, scraping configurations, and rule files

global:
  scrape_interval: 15s     # How frequently to scrape targets
  evaluation_interval: 15s  # How frequently to evaluate rules
  scrape_timeout: 10s      # How long until a scrape request times out

# Rule files containing recording and alerting rules
rule_files:
  - "rules/alerts.yml"     # Alert rules configuration
  - "rules/recording.yml"  # Recording rules configuration

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: 'https'
      timeout: '10s'
      api_version: 'v2'
      tls_config:
        cert_file: '/etc/prometheus/certs/client.crt'
        key_file: '/etc/prometheus/certs/client.key'
        ca_file: '/etc/prometheus/certs/ca.crt'

# Storage configuration
storage:
  tsdb:
    retention_time: '15d'    # How long to retain data
    retention_size: '50GB'   # Maximum storage size
    wal_compression: true    # Enable WAL compression
    min_block_duration: '2h' # Minimum block duration
    max_block_duration: '24h' # Maximum block duration

# Scrape configurations
scrape_configs:
  # API Gateway monitoring
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['api-gateway:8080']
    relabel_configs:
      - source_labels: ['__meta_kubernetes_pod_label_app']
        target_label: 'app'

  # Transcription Service monitoring
  - job_name: 'transcription-service'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['transcription-service:8081']

  # AI Engine monitoring
  - job_name: 'ai-engine'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['ai-engine:8082']

  # Document Service monitoring
  - job_name: 'document-service'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['document-service:8083']

  # Distribution Service monitoring
  - job_name: 'distribution-service'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['distribution-service:8084']