apiVersion: v1
kind: Secret
metadata:
  name: meeting-minutes-secrets
  namespace: meeting-minutes
  labels:
    app: meeting-minutes
    environment: production
    managed-by: azure-key-vault
    rotation-policy: 90-days
    security-tier: high
  annotations:
    azure.key-vault/enabled: "true"
    azure.key-vault/vault-name: "meeting-minutes-kv"
    azure.key-vault/polling-interval: "1h"
    security.compliance/encryption: "aes-256"
    security.compliance/audit-enabled: "true"
type: Opaque
data:
  # API Gateway Secrets
  # Used for authentication, authorization and security controls
  api-gateway-secrets:
    JWT_SECRET: ${JWT_SECRET}
    AZURE_AD_CLIENT_SECRET: ${AZURE_AD_CLIENT_SECRET}
    AZURE_AD_TENANT_ID: ${AZURE_AD_TENANT_ID}
    API_KEY: ${API_GATEWAY_API_KEY}
    RATE_LIMIT_SECRET: ${RATE_LIMIT_SECRET}
    WAF_CONFIGURATION: ${WAF_CONFIG}

  # Transcription Service Secrets
  # Used for Teams integration and data storage
  transcription-service-secrets:
    TEAMS_API_KEY: ${TEAMS_API_KEY}
    AZURE_STORAGE_CONNECTION_STRING: ${TRANSCRIPTION_STORAGE_CONN}
    DATABASE_CONNECTION_STRING: ${TRANSCRIPTION_DB_CONN}
    BLOB_ENCRYPTION_KEY: ${TRANSCRIPTION_ENCRYPTION_KEY}
    SERVICE_BUS_CONNECTION: ${TRANSCRIPTION_SB_CONN}

  # AI Engine Secrets
  # Used for ML model access and cognitive services
  ai-engine-secrets:
    MODEL_API_KEY: ${AI_MODEL_KEY}
    AZURE_COGNITIVE_SERVICES_KEY: ${COGNITIVE_SERVICES_KEY}
    DATABASE_CONNECTION_STRING: ${AI_DB_CONN}
    GPU_ACCESS_KEY: ${GPU_ACCESS_KEY}
    MODEL_ENCRYPTION_KEY: ${MODEL_ENCRYPTION_KEY}

  # Document Service Secrets
  # Used for document generation and storage
  document-service-secrets:
    AZURE_STORAGE_CONNECTION_STRING: ${DOCUMENT_STORAGE_CONN}
    DATABASE_CONNECTION_STRING: ${DOCUMENT_DB_CONN}
    ENCRYPTION_KEY: ${DOCUMENT_ENCRYPTION_KEY}
    DOCUMENT_SIGNING_KEY: ${DOCUMENT_SIGNING_KEY}
    PDF_GENERATION_KEY: ${PDF_KEY}

  # Distribution Service Secrets
  # Used for email and notification delivery
  distribution-service-secrets:
    SMTP_PASSWORD: ${SMTP_PASSWORD}
    TEAMS_WEBHOOK_URL: ${TEAMS_WEBHOOK_URL}
    DATABASE_CONNECTION_STRING: ${DISTRIBUTION_DB_CONN}
    AZURE_SERVICE_BUS_CONNECTION_STRING: ${DISTRIBUTION_SB_CONN}
    EMAIL_ENCRYPTION_KEY: ${EMAIL_ENCRYPTION_KEY}
    NOTIFICATION_SIGNING_KEY: ${NOTIFICATION_SIGNING_KEY}