# Tempo Configuration v2.1.0
# Distributed tracing configuration for the Automated Meeting Minutes System
# Defines trace collection, storage, and retention policies

server:
  http_listen_port: 3200
  grpc_listen_port: 9095
  http_server_read_timeout: "30s"
  http_server_write_timeout: "30s"
  grpc_server_max_recv_msg_size: "4MB"
  grpc_server_max_send_msg_size: "4MB"

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: "0.0.0.0:14268"
        grpc:
          endpoint: "0.0.0.0:14250"
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:4318"
        grpc:
          endpoint: "0.0.0.0:4317"

ingester:
  max_block_duration: "2h"  # Aligned with global configuration
  complete_block_timeout: "30m"
  flush_check_period: "1m"

compactor:
  compaction:
    block_retention: "336h"  # 14 days retention aligned with global configuration
    compacted_block_retention: "1h"
    compaction_window: "1h"
    max_compaction_objects: 1000000
    block_retention_concurrency: 10

storage:
  trace:
    backend: "local"  # Local storage backend configuration
    local:
      path: "/tmp/tempo/blocks"
    pool:
      max_workers: 100
      queue_depth: 10000

overrides:
  max_bytes_per_trace: "50MB"
  max_bytes_per_tag_values_query: "5MB"
  max_search_bytes_per_trace: "5MB"

# Integration with Prometheus service discovery
search_enabled: true
metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: meeting-minutes-system
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

# Multitenancy configuration
multitenancy_enabled: true
auth_enabled: true

# Query frontend configuration
query_frontend:
  search:
    max_duration: "336h"  # Aligned with retention period
  trace_by_id:
    query_timeout: "30s"

# Live tailing configuration
live_tailing_enabled: true
live_tailing_config:
  max_duration: "1h"